version: '3.8'

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass12345
      MONGO_INITDB_DATABASE: restuarant_db
    ports:
      - "27017:27017"
    networks:
      - restuarant_net
    volumes:
      - /mongostore/datadir:/data/db

    # docker run -it --rm --network <network-name> mongodb mongosh --host mongodb -u <username> -p <secret> --authenticateDatabase admin <dbname>
  
  monogo-express:
    restart: always
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass12345
      ME_CONFIG_MONGODB_URL: mongodb://root:pass12345@mongodb:27017/
    networks:
      - restuarant_net

networks:
  restuarant_net: